/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifrn.atvd;

import javax.swing.JOptionPane;

/**
 *
 * @author 20181114010040
 */
public class Teste extends javax.swing.JFrame {

    /**
     * Creates new form Teste
     */
    public Teste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaQuadroMens = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfConsumo = new javax.swing.JTextField();
        jtfCapacidade = new javax.swing.JTextField();
        jtfTanque = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jrbCarro = new javax.swing.JRadioButton();
        jrbMoto = new javax.swing.JRadioButton();
        jrbAndar = new javax.swing.JButton();
        jrbAbastecer = new javax.swing.JButton();
        jrbConsultarTanque = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtaQuadroMens.setColumns(20);
        jtaQuadroMens.setRows(5);
        jScrollPane1.setViewportView(jtaQuadroMens);

        jPanel2.setBackground(new java.awt.Color(120, 211, 235));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText(" Simulador de veículos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Consumo/L:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Capacidade Total:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tanque:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Selecione um veículo:");

        buttonGroup1.add(jrbCarro);
        jrbCarro.setText("Carro");
        jrbCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCarroActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbMoto);
        jrbMoto.setText("Moto");
        jrbMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMotoActionPerformed(evt);
            }
        });

        jrbAndar.setBackground(new java.awt.Color(186, 219, 231));
        jrbAndar.setText("Andar");
        jrbAndar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAndarActionPerformed(evt);
            }
        });

        jrbAbastecer.setBackground(new java.awt.Color(173, 221, 227));
        jrbAbastecer.setText("Abastecer");
        jrbAbastecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAbastecerActionPerformed(evt);
            }
        });

        jrbConsultarTanque.setBackground(new java.awt.Color(176, 218, 231));
        jrbConsultarTanque.setText("Consultar Tanque");
        jrbConsultarTanque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbConsultarTanqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfConsumo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCapacidade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTanque))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(85, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbCarro)
                                .addGap(18, 18, 18)
                                .addComponent(jrbMoto)))
                        .addGap(177, 177, 177))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jrbAndar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbAbastecer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrbConsultarTanque)))
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfTanque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCarro)
                    .addComponent(jrbMoto))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAndar)
                    .addComponent(jrbAbastecer)
                    .addComponent(jrbConsultarTanque))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCarroActionPerformed
        if (jrbCarro.isSelected()) {
            jrbAndar.setEnabled(true);
            jrbAbastecer.setEnabled(true);
            jrbConsultarTanque.setEnabled(true);
        }
    }//GEN-LAST:event_jrbCarroActionPerformed

    private void jrbMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMotoActionPerformed
        if (jrbMoto.isSelected()) {
            jrbAndar.setEnabled(true);
            jrbAbastecer.setEnabled(true);
            jrbConsultarTanque.setEnabled(true);
        }
    }//GEN-LAST:event_jrbMotoActionPerformed

    private void jrbAndarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAndarActionPerformed
        if (jrbCarro.isSelected()) {
            if (carro == null) {

                
                int consumo = Integer.parseInt(jtfConsumo.getText());
                int capacidade = Integer.parseInt(jtfCapacidade.getText());

                carro = new Carro(consumo, capacidade, 0);
            }
            
            String distancia = JOptionPane.showInputDialog(this, "Digite a distância que você quer andar:");
            
            if (distancia != null) {
                int dist = Integer.parseInt(distancia);

                jtaQuadroMens.append("\n" + carro.andar(dist));

            }
        }

        if (jrbMoto.isSelected()) {
            if (moto == null) {
                int consumo = Integer.parseInt(jtfConsumo.getText());
                int capacidade = Integer.parseInt(jtfCapacidade.getText());

                moto = new Moto(consumo, capacidade, 0);
            }
            
            String distancia = JOptionPane.showInputDialog(this, "Digite a distância que você quer andar:");
            
            if (distancia != null) {
                int dist = Integer.parseInt(distancia);

                jtaQuadroMens.append("\n" + moto.andar(dist));
            }
        }
    }//GEN-LAST:event_jrbAndarActionPerformed

    private void jrbAbastecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAbastecerActionPerformed

        if (jrbCarro.isSelected()) {
            if (carro == null) {

                int tanque = Integer.parseInt(jtfTanque.getText());
                int consumo = Integer.parseInt(jtfConsumo.getText());
                int capacidade = Integer.parseInt(jtfCapacidade.getText());

                carro = new Carro(consumo, capacidade, tanque);
            }

            String litros = JOptionPane.showInputDialog(this, "Digite quantos litros você quer abastecer:");

            int lit = Integer.parseInt(litros);

            jtaQuadroMens.append("\n" + carro.abastecer(lit));
        }

        if (jrbMoto.isSelected()) {
            if (moto == null) {

                int tanque = Integer.parseInt(jtfTanque.getText());
                int consumo = Integer.parseInt(jtfConsumo.getText());
                int capacidade = Integer.parseInt(jtfCapacidade.getText());

                moto = new Moto(consumo, capacidade, tanque);

            }

            String litros = JOptionPane.showInputDialog(this, "Digite quantos litros você quer abastecer:");

            int lit = Integer.parseInt(litros);

            jtaQuadroMens.append("\n" + moto.abastecer(lit));
        }

    }//GEN-LAST:event_jrbAbastecerActionPerformed

    private void jrbConsultarTanqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbConsultarTanqueActionPerformed
        if (jrbCarro.isSelected()) {
            if (carro == null) {

                int tanque = Integer.parseInt(jtfTanque.getText());
                int consumo = Integer.parseInt(jtfConsumo.getText());
                int capacidade = Integer.parseInt(jtfCapacidade.getText());

                carro = new Carro(consumo, capacidade, tanque);
            }

            jtaQuadroMens.append("\nO tanque está com " + carro.consultarTanque() + "L");

        }

        if (jrbMoto.isSelected()) {
            if (moto == null) {

                int tanque = Integer.parseInt(jtfTanque.getText());
                int consumo = Integer.parseInt(jtfConsumo.getText());
                int capacidade = Integer.parseInt(jtfCapacidade.getText());

                moto = new Moto(consumo, capacidade, tanque);
            }

            jtaQuadroMens.append("\nO tanque está com " + moto.consultarTanque() + "L");

        }
    }//GEN-LAST:event_jrbConsultarTanqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jrbAbastecer;
    private javax.swing.JButton jrbAndar;
    private javax.swing.JRadioButton jrbCarro;
    private javax.swing.JButton jrbConsultarTanque;
    private javax.swing.JRadioButton jrbMoto;
    private javax.swing.JTextArea jtaQuadroMens;
    private javax.swing.JTextField jtfCapacidade;
    private javax.swing.JTextField jtfConsumo;
    private javax.swing.JTextField jtfTanque;
    // End of variables declaration//GEN-END:variables
    private Carro carro;
    private Moto moto;
}
